baseURL = 'https://valery.nivelais.com/'
languageCode = 'en-us'
title = 'Valery Nivelais'
theme = 'hello-friend-ng'

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
    name = "Valery Nivelais"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Seo
    description = "Explore in-depth articles, tutorials, and insights on Solidity, smart contract security, and gas optimisations."
    keywords = "solidity, smart contracts, gas optimisation, security, blockchain, ethereum, programming, development, dApp, tutorials, articles, ERC-20, EIP-712, ERC-2612"

    # Subtitle for the home page
    homeSubtitle = "Piscine & CTO @frak-labs"

    # For build info
    gitUrl = "https://github.com/Rubikson/Rubikson.github.io/"

    # For the theme toggle
    enableThemeToggle = true

    # For the share buttons
    enableSharingButtons = false

    # For the language toggle
    enableGlobalLanguageMenu = false

    # For text alignment
    justifyContent = true

    # Import our custom css script
    customCSS = ["/css/style.css"]

# Header logo
[params.logo]
    logoMark     = ">"
    logoText     = "$  Netlor"
    logoHomeLink = "/"
    logoCursorPathname = true

# Add portrait to home page
[params.portrait]
    path     = "/img/portrait.webp"
    alt      = "Portrait"
    maxWidth = "200px"

# Add footer
[params.footer]
    trademark = true
    author = true

[menu]
    [[menu.main]]
        identifier = "articles"
        name       = "Articles"
        url        = "articles/"


# Social networks
[[params.social]]
    name = "email"
    url = "mailto:valery@nivelais.com"

[[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/quentin-nivelais-5081a4141/"
