baseURL = 'https://valery.nivelais.com/'
languageCode = 'en-us'
title = 'Valery Nivelais'
theme = 'hello-friend-ng'

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
    name = "Valery Nivelais"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Seo
    description = "Expertise en management d'équipe"
    keywords = "management, consultant,expert,management,conseil,Piscine,sport aquatique, maitre nageur"

    # Subtitle for the home page
    homeSubtitle = "Manager de proximité"

    # For build info
    gitUrl = "https://github.com/Rubikson/Rubikson.github.io/"

    # For the theme toggle
    enableThemeToggle = true

    # For the share buttons
    enableSharingButtons = false

    # For the language toggle
    enableGlobalLanguageMenu = false

    # For text alignment
    justifyContent = true

    # Import our custom css script
    customCSS = ["/css/style.css"]

# Header logo
[params.logo]
    logoMark     = ">"
    logoText     = "VN entreprise " 
    
    
    logoHomeLink = "/"
    logoCursorPathname = false

# Add square portrait to home page
[
params.portrait
]
    path     = "/img/val1.jpg"
    alt      = "portrait"
    maxWidth = "300px"
    maxHeight = "300px"
    style    = "object-fit: cover; width: 300px; height: 300px;"
 

# Add footer
[params.footer]
    trademark = true
    author = true

[menu]
    [[menu.main]]
        identifier = "about"
        name       = "info"
        url        = "info/"
       #[[menu.main]]
        #identifier = "tarifs"
        #name       = "tarifs"
        #url        = "tarifs/"
        


# Social networks
[[params.social]]
    name = "email"
    url = "mailto:valery@nivelais.com"

[[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/valéry-n-1974985b/"
