baseURL = 'https://quentin.nivelais.com/'
languageCode = 'en-us'
title = 'Quentin Nivelais'
theme = 'hello-friend-ng'

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
    name = "Quentin Nivelais"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Seo
    description = "Explore in-depth articles, tutorials, and insights on Solidity, smart contract security, and gas optimisations."
    keywords = "solidity, smart contracts, gas optimisation, security, blockchain, ethereum, programming, development"

    # Subtitle for the home page
    homeSubtitle = "CoFounder & CTO @frak-labs | EVM Pro | Rust Learner"

    # For build info
    gitUrl = "https://github.com/KONFeature/KONFeature.github.io/commit/"

    # For the theme toggle
    enableThemeToggle = true

    # For the share buttons
    enableSharingButtons = false

    # For the language toggle
    enableGlobalLanguageMenu = false

    # For text alignment
    justifyContent = true

    # Import our custom css script
    customCSS = ["/css/style.css"]

# Header logo
[params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    logoCursorPathname = true

# Add portrait to home page
[params.portrait]
    path     = "/img/portrait.png"
    alt      = "Portrait"
    maxWidth = "200px"

# Add footer
[params.footer]
    trademark = false
    author = true

[menu]
    [[menu.main]]
        identifier = "articles"
        name       = "Articles"
        url        = "articles/"
    [[menu.main]]
        identifier = "threads"
        name       = "Threads"
        url        = "threads/"


# Social networks
[[params.social]]
    name = "github"
    url = "https://github.com/KONFeature"

[[params.social]]
    name = "X"
    url = "https://x.com/QNivelais"

[[params.social]]
    name = "medium"
    url = "https://medium.com/@quentin.nivelais"

[[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/quentin-nivelais-5081a4141/"
